# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcoN5T6ZzA-CHM3BgRjkbk1mIHtrtv-d
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile farrel074.py
# 
# def perkalian_matriks(m1, m2):
#     if len(m1[0]) != len(m2):
#         return "Matriks tidak dapat dikalikan"
# 
#     hasil = []
# 
#     for i in range(len(m1)):
#         baris = []
#         for j in range(len(m2[0])):
#             total = 0
#             for k in range(len(m2)):
#                 total += m1[i][k] * m2[k][j]
#             baris.append(total)
#         hasil.append(baris)
# 
#     return hasil
# 
# 
# def transpose_matriks(matriks):
#     hasil = []
# 
#     for i in range(len(matriks[0])):
#         baris = []
#         for j in range(len(matriks)):
#             baris.append(matriks[j][i])
#         hasil.append(baris)
# 
#     return hasil
# 
# 
#

import farrel074

# Matriks pertama
A = [
    [1, 2, 3],
    [4, 5, 6]
]

# Matriks kedua
B = [
    [7, 8],
    [9, 10],
    [11, 12]
]

# Perkalian matriks
hasil_kali = farrel074.perkalian_matriks(A, B)

print("Hasil Perkalian Matriks:")
for row in hasil_kali:
    print(row)

# Transpose matriks
print("\nTranspose Matriks A:")
hasil_transpose = farrel074.transpose_matriks(A)

for row in hasil_transpose:
    print(row)